workan on image dump tools and xrdp a desktop over windows

diff --git a/customscripts/prepare_for_release_img,sh b/customscripts/prepare_for_release_img,sh
--- a/customscripts/prepare_for_release_img,sh
+++ b/customscripts/prepare_for_release_img,sh
@@ -1,6 +1,15 @@
 #!/bin/bash
+# updoot and clean up package shit
+# notably not upgrading for stability
+sudo apt update
+sudo apt autoremove -y
+
+user=princesspi
+userhome=/home/$princesspi
+zero_file_path="$userhome/0.0"
+
 echo "nukan .ssh and github token"
-rm -rf $HOME/.ssh $HOME/.gh_token
+rm -rf "$userhome/.ssh" "$userhome/.gh_token"
 
 echo "logging out of github"
 gh auth logout
@@ -9,15 +18,19 @@ echo "removing user.name and user.email from git configs"
 git config --unset user.name
 git config --unset user.email
 
-echo "change pass to princesspi"
-passwd
+echo "change pass to $user"
+passwd $user
 
 echo "now to set pw to be reset on first login"
-sudo passwd -e princesspi
+sudo passwd -e $user
 
 echo "zeroing out all da fuckin space fuuck"
-zero_file_path="$HOME/0.0"
-sudo dd if=/dev/zero bs=4M status=progress > "$zero_file_path" || echo -e "$zero_file_path file reached max size, deleting"; sudo rm -f "$zero_file_path"; echo -e "retcode: $?"
+zero_file_path="$userhome/0.0"
+if ! sudo dd if=/dev/zero bs=4M status=progress > "$zero_file_path"; then
+    echo -e "$zero_file_path file reached max size, deleting"
+    sudo rm -f "$zero_file_path"
+    echo -e "delete file retcode: retcode: $?"
+fi
 
 echo "thank fuck that fucking ended"
 
